x = {u'cache_ts': 1491417883, u'ok': True, u'members': [{u'status': None,
                                                         u'profile': {u'first_name': u'Quinn', u'last_name': u'Neal',
                                                                      u'image_1024': u'https://avatars.slack-edge.com/2017-01-13/127359218835_e925cff7c33b13fbdc8b_512.jpg',
                                                                      u'real_name': u'Quinn Neal',
                                                                      u'image_24': u'https://avatars.slack-edge.com/2017-01-13/127359218835_e925cff7c33b13fbdc8b_24.jpg',
                                                                      u'image_original': u'https://avatars.slack-edge.com/2017-01-13/127359218835_e925cff7c33b13fbdc8b_original.jpg',
                                                                      u'real_name_normalized': u'Quinn Neal',
                                                                      u'image_512': u'https://avatars.slack-edge.com/2017-01-13/127359218835_e925cff7c33b13fbdc8b_512.jpg',
                                                                      u'image_32': u'https://avatars.slack-edge.com/2017-01-13/127359218835_e925cff7c33b13fbdc8b_32.jpg',
                                                                      u'image_48': u'https://avatars.slack-edge.com/2017-01-13/127359218835_e925cff7c33b13fbdc8b_48.jpg',
                                                                      u'image_72': u'https://avatars.slack-edge.com/2017-01-13/127359218835_e925cff7c33b13fbdc8b_72.jpg',
                                                                      u'avatar_hash': u'e925cff7c33b',
                                                                      u'email': u'quinnfergusgryphon@gmail.com',
                                                                      u'image_192': u'https://avatars.slack-edge.com/2017-01-13/127359218835_e925cff7c33b13fbdc8b_192.jpg'},
                                                         u'updated': 1484336755, u'tz': u'America/Chicago',
                                                         u'name': u'a_very_sad_dm', u'deleted': False, u'is_bot': False,
                                                         u'tz_label': u'Central Daylight Time',
                                                         u'real_name': u'Quinn Neal', u'color': u'3c989f',
                                                         u'team_id': u'T3Q3WR7RN', u'is_admin': False,
                                                         u'is_ultra_restricted': False, u'is_restricted': False,
                                                         u'is_owner': False, u'tz_offset': -18000, u'id': u'U3QS0AVNE',
                                                         u'is_primary_owner': False}, {u'status': None, u'profile': {
    u'first_name': u'Ezra', u'last_name': u'Neal',
    u'image_1024': u'https://avatars.slack-edge.com/2017-01-12/126968682500_c07ba4457f0cb5e7811a_512.jpg',
    u'real_name': u'Ezra Neal',
    u'image_24': u'https://avatars.slack-edge.com/2017-01-12/126968682500_c07ba4457f0cb5e7811a_24.jpg',
    u'image_original': u'https://avatars.slack-edge.com/2017-01-12/126968682500_c07ba4457f0cb5e7811a_original.jpg',
    u'real_name_normalized': u'Ezra Neal',
    u'image_512': u'https://avatars.slack-edge.com/2017-01-12/126968682500_c07ba4457f0cb5e7811a_512.jpg',
    u'image_32': u'https://avatars.slack-edge.com/2017-01-12/126968682500_c07ba4457f0cb5e7811a_32.jpg',
    u'image_48': u'https://avatars.slack-edge.com/2017-01-12/126968682500_c07ba4457f0cb5e7811a_48.jpg',
    u'image_72': u'https://avatars.slack-edge.com/2017-01-12/126968682500_c07ba4457f0cb5e7811a_72.jpg',
    u'avatar_hash': u'c07ba4457f0c', u'email': u'ezra.g.d.neal@gmail.com',
    u'image_192': u'https://avatars.slack-edge.com/2017-01-12/126968682500_c07ba4457f0cb5e7811a_192.jpg'},
                                                                                       u'updated': 1484252017,
                                                                                       u'tz': u'America/Chicago',
                                                                                       u'name': u'ezra',
                                                                                       u'deleted': False,
                                                                                       u'is_bot': False,
                                                                                       u'tz_label': u'Central Daylight Time',
                                                                                       u'real_name': u'Ezra Neal',
                                                                                       u'color': u'9f69e7',
                                                                                       u'team_id': u'T3Q3WR7RN',
                                                                                       u'is_admin': True,
                                                                                       u'is_ultra_restricted': False,
                                                                                       u'is_restricted': False,
                                                                                       u'is_owner': True,
                                                                                       u'tz_offset': -18000,
                                                                                       u'id': u'U3RF8GV0W',
                                                                                       u'is_primary_owner': True},
                                                        {u'status': None, u'profile': {u'first_name': u'Isami',
                                                                                       u'last_name': u'Romanowski',
                                                                                       u'real_name': u'Isami Romanowski',
                                                                                       u'image_24': u'https://secure.gravatar.com/avatar/051668394de64ff222e53678fde0d1d3.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0026-24.png',
                                                                                       u'real_name_normalized': u'Isami Romanowski',
                                                                                       u'image_512': u'https://secure.gravatar.com/avatar/051668394de64ff222e53678fde0d1d3.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0026-512.png',
                                                                                       u'image_32': u'https://secure.gravatar.com/avatar/051668394de64ff222e53678fde0d1d3.jpg?s=32&d=https%3A%2F%2Fa.slack-edge.com%2F0180%2Fimg%2Favatars%2Fava_0026-32.png',
                                                                                       u'image_48': u'https://secure.gravatar.com/avatar/051668394de64ff222e53678fde0d1d3.jpg?s=48&d=https%3A%2F%2Fa.slack-edge.com%2F272a%2Fimg%2Favatars%2Fava_0026-48.png',
                                                                                       u'image_72': u'https://secure.gravatar.com/avatar/051668394de64ff222e53678fde0d1d3.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0026-72.png',
                                                                                       u'avatar_hash': u'g051668394de',
                                                                                       u'email': u'isami.romanowski@gmail.com',
                                                                                       u'image_192': u'https://secure.gravatar.com/avatar/051668394de64ff222e53678fde0d1d3.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0026-192.png'},
                                                         u'updated': 1484363406, u'tz': u'America/Los_Angeles',
                                                         u'name': u'isami', u'deleted': False, u'is_bot': False,
                                                         u'tz_label': u'Pacific Daylight Time',
                                                         u'real_name': u'Isami Romanowski', u'color': u'e0a729',
                                                         u'team_id': u'T3Q3WR7RN', u'is_admin': False,
                                                         u'is_ultra_restricted': False, u'is_restricted': False,
                                                         u'is_owner': False, u'tz_offset': -25200, u'id': u'U3S7J0W0P',
                                                         u'is_primary_owner': False}, {u'status': None, u'profile': {
        u'first_name': u'Matthew', u'last_name': u'Maluschka', u'real_name': u'Matthew Maluschka',
        u'image_24': u'https://secure.gravatar.com/avatar/c2f71a273f7ffc0a08e213e942bdbe93.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0016-24.png',
        u'real_name_normalized': u'Matthew Maluschka',
        u'image_512': u'https://secure.gravatar.com/avatar/c2f71a273f7ffc0a08e213e942bdbe93.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0016-512.png',
        u'image_32': u'https://secure.gravatar.com/avatar/c2f71a273f7ffc0a08e213e942bdbe93.jpg?s=32&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0016-32.png',
        u'image_48': u'https://secure.gravatar.com/avatar/c2f71a273f7ffc0a08e213e942bdbe93.jpg?s=48&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0016-48.png',
        u'image_72': u'https://secure.gravatar.com/avatar/c2f71a273f7ffc0a08e213e942bdbe93.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0016-72.png',
        u'avatar_hash': u'gc2f71a273f7', u'email': u'hdntiger@sbcglobal.net',
        u'image_192': u'https://secure.gravatar.com/avatar/c2f71a273f7ffc0a08e213e942bdbe93.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0016-192.png'},
                                                                                       u'updated': 1484274946,
                                                                                       u'tz': u'America/Chicago',
                                                                                       u'name': u'like_20_newbs',
                                                                                       u'deleted': False,
                                                                                       u'is_bot': False,
                                                                                       u'tz_label': u'Central Daylight Time',
                                                                                       u'real_name': u'Matthew Maluschka',
                                                                                       u'color': u'e96699',
                                                                                       u'team_id': u'T3Q3WR7RN',
                                                                                       u'is_admin': False,
                                                                                       u'is_ultra_restricted': False,
                                                                                       u'is_restricted': False,
                                                                                       u'is_owner': False,
                                                                                       u'tz_offset': -18000,
                                                                                       u'id': u'U3RMHNNQP',
                                                                                       u'is_primary_owner': False},
                                                        {u'status': None,
                                                         u'profile': {u'first_name': u'Philip', u'last_name': u'Green',
                                                                      u'image_1024': u'https://avatars.slack-edge.com/2017-01-13/126696935553_099e5241263b641b9d97_1024.png',
                                                                      u'real_name': u'Philip Green',
                                                                      u'image_24': u'https://avatars.slack-edge.com/2017-01-13/126696935553_099e5241263b641b9d97_24.png',
                                                                      u'image_original': u'https://avatars.slack-edge.com/2017-01-13/126696935553_099e5241263b641b9d97_original.png',
                                                                      u'real_name_normalized': u'Philip Green',
                                                                      u'image_512': u'https://avatars.slack-edge.com/2017-01-13/126696935553_099e5241263b641b9d97_512.png',
                                                                      u'image_32': u'https://avatars.slack-edge.com/2017-01-13/126696935553_099e5241263b641b9d97_32.png',
                                                                      u'image_48': u'https://avatars.slack-edge.com/2017-01-13/126696935553_099e5241263b641b9d97_48.png',
                                                                      u'image_72': u'https://avatars.slack-edge.com/2017-01-13/126696935553_099e5241263b641b9d97_72.png',
                                                                      u'avatar_hash': u'099e5241263b',
                                                                      u'email': u'pgreen.78633@gmail.com',
                                                                      u'image_192': u'https://avatars.slack-edge.com/2017-01-13/126696935553_099e5241263b641b9d97_192.png'},
                                                         u'updated': 1484331099, u'tz': u'America/Chicago',
                                                         u'name': u'phil', u'deleted': False, u'is_bot': False,
                                                         u'tz_label': u'Central Daylight Time',
                                                         u'real_name': u'Philip Green', u'color': u'674b1b',
                                                         u'team_id': u'T3Q3WR7RN', u'is_admin': False,
                                                         u'is_ultra_restricted': False, u'is_restricted': False,
                                                         u'is_owner': False, u'tz_offset': -18000, u'id': u'U3Q5D3NM6',
                                                         u'is_primary_owner': False}, {u'status': None,
                                                                                       u'profile': {u'api_app_id': u'',
                                                                                                    u'image_1024': u'https://avatars.slack-edge.com/2017-04-05/164308185152_7c862cd2d087b79b2fbf_1024.png',
                                                                                                    u'real_name': u'',
                                                                                                    u'image_24': u'https://avatars.slack-edge.com/2017-04-05/164308185152_7c862cd2d087b79b2fbf_24.png',
                                                                                                    u'image_original': u'https://avatars.slack-edge.com/2017-04-05/164308185152_7c862cd2d087b79b2fbf_original.png',
                                                                                                    u'real_name_normalized': u'',
                                                                                                    u'image_512': u'https://avatars.slack-edge.com/2017-04-05/164308185152_7c862cd2d087b79b2fbf_512.png',
                                                                                                    u'image_32': u'https://avatars.slack-edge.com/2017-04-05/164308185152_7c862cd2d087b79b2fbf_32.png',
                                                                                                    u'image_48': u'https://avatars.slack-edge.com/2017-04-05/164308185152_7c862cd2d087b79b2fbf_48.png',
                                                                                                    u'image_72': u'https://avatars.slack-edge.com/2017-04-05/164308185152_7c862cd2d087b79b2fbf_72.png',
                                                                                                    u'avatar_hash': u'7c862cd2d087',
                                                                                                    u'image_192': u'https://avatars.slack-edge.com/2017-04-05/164308185152_7c862cd2d087b79b2fbf_192.png',
                                                                                                    u'always_active': False,
                                                                                                    u'bot_id': u'B4V32HFKP'},
                                                                                       u'updated': 1491412412,
                                                                                       u'tz': None,
                                                                                       u'name': u'starterbot',
                                                                                       u'deleted': False,
                                                                                       u'is_bot': True,
                                                                                       u'tz_label': u'Pacific Daylight Time',
                                                                                       u'real_name': u'',
                                                                                       u'color': u'684b6c',
                                                                                       u'team_id': u'T3Q3WR7RN',
                                                                                       u'is_admin': False,
                                                                                       u'is_ultra_restricted': False,
                                                                                       u'is_restricted': False,
                                                                                       u'is_owner': False,
                                                                                       u'tz_offset': -25200,
                                                                                       u'id': u'U4U92534G',
                                                                                       u'is_primary_owner': False},
                                                        {u'status': None,
                                                         u'profile': {u'first_name': u'Lance', u'last_name': u'Q',
                                                                      u'real_name': u'Lance Q',
                                                                      u'image_24': u'https://secure.gravatar.com/avatar/c1228996f5295441896a3d7b6c2e1259.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F0180%2Fimg%2Favatars%2Fava_0025-24.png',
                                                                      u'real_name_normalized': u'Lance Q',
                                                                      u'image_512': u'https://secure.gravatar.com/avatar/c1228996f5295441896a3d7b6c2e1259.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0025-512.png',
                                                                      u'image_32': u'https://secure.gravatar.com/avatar/c1228996f5295441896a3d7b6c2e1259.jpg?s=32&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0025-32.png',
                                                                      u'image_48': u'https://secure.gravatar.com/avatar/c1228996f5295441896a3d7b6c2e1259.jpg?s=48&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0025-48.png',
                                                                      u'image_72': u'https://secure.gravatar.com/avatar/c1228996f5295441896a3d7b6c2e1259.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0025-72.png',
                                                                      u'avatar_hash': u'gc1228996f52',
                                                                      u'email': u'ndnlanceq@gmail.com',
                                                                      u'image_192': u'https://secure.gravatar.com/avatar/c1228996f5295441896a3d7b6c2e1259.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0025-192.png'},
                                                         u'updated': 1484251218, u'tz': u'America/Chicago',
                                                         u'name': u'thaysohngaw', u'deleted': False, u'is_bot': False,
                                                         u'tz_label': u'Central Daylight Time',
                                                         u'real_name': u'Lance Q', u'color': u'e7392d',
                                                         u'team_id': u'T3Q3WR7RN', u'is_admin': False,
                                                         u'is_ultra_restricted': False, u'is_restricted': False,
                                                         u'is_owner': False, u'tz_offset': -18000, u'id': u'U3RGK7L3G',
                                                         u'is_primary_owner': False}, {u'status': None, u'profile': {
        u'first_name': u'Hadolf', u'last_name': u'Aitler', u'real_name': u'Hadolf Aitler',
        u'image_24': u'https://secure.gravatar.com/avatar/c85ea71cdd04a4e879134f5b99f3c558.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F0180%2Fimg%2Favatars%2Fava_0004-24.png',
        u'real_name_normalized': u'Hadolf Aitler',
        u'image_512': u'https://secure.gravatar.com/avatar/c85ea71cdd04a4e879134f5b99f3c558.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0004-512.png',
        u'image_32': u'https://secure.gravatar.com/avatar/c85ea71cdd04a4e879134f5b99f3c558.jpg?s=32&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0004-32.png',
        u'image_48': u'https://secure.gravatar.com/avatar/c85ea71cdd04a4e879134f5b99f3c558.jpg?s=48&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0004-48.png',
        u'image_72': u'https://secure.gravatar.com/avatar/c85ea71cdd04a4e879134f5b99f3c558.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0004-72.png',
        u'avatar_hash': u'gc85ea71cdd0', u'email': u'tran.dennis92@yahoo.com',
        u'image_192': u'https://secure.gravatar.com/avatar/c85ea71cdd04a4e879134f5b99f3c558.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0004-192.png'},
                                                                                       u'updated': 1484247834,
                                                                                       u'tz': u'America/Chicago',
                                                                                       u'name': u'thisisstupid',
                                                                                       u'deleted': False,
                                                                                       u'is_bot': False,
                                                                                       u'tz_label': u'Central Daylight Time',
                                                                                       u'real_name': u'Hadolf Aitler',
                                                                                       u'color': u'4bbe2e',
                                                                                       u'team_id': u'T3Q3WR7RN',
                                                                                       u'is_admin': False,
                                                                                       u'is_ultra_restricted': False,
                                                                                       u'is_restricted': False,
                                                                                       u'is_owner': False,
                                                                                       u'tz_offset': -18000,
                                                                                       u'id': u'U3QP0UNTV',
                                                                                       u'is_primary_owner': False},
                                                        {u'status': None,
                                                         u'profile': {u'first_name': u'slackbot', u'last_name': u'',
                                                                      u'fields': None, u'real_name': u'slackbot',
                                                                      u'image_24': u'https://a.slack-edge.com/0180/img/slackbot_24.png',
                                                                      u'real_name_normalized': u'slackbot',
                                                                      u'image_512': u'https://a.slack-edge.com/1801/img/slackbot_512.png',
                                                                      u'image_32': u'https://a.slack-edge.com/2fac/plugins/slackbot/assets/service_32.png',
                                                                      u'image_48': u'https://a.slack-edge.com/2fac/plugins/slackbot/assets/service_48.png',
                                                                      u'avatar_hash': u'sv1444671949',
                                                                      u'image_72': u'https://a.slack-edge.com/0180/img/slackbot_72.png',
                                                                      u'always_active': True,
                                                                      u'image_192': u'https://a.slack-edge.com/66f9/img/slackbot_192.png'},
                                                         u'updated': 0, u'tz': None, u'name': u'slackbot',
                                                         u'deleted': False, u'is_bot': False,
                                                         u'tz_label': u'Pacific Daylight Time',
                                                         u'real_name': u'slackbot', u'color': u'757575',
                                                         u'team_id': u'T3Q3WR7RN', u'is_admin': False,
                                                         u'is_ultra_restricted': False, u'is_restricted': False,
                                                         u'is_owner': False, u'tz_offset': -25200, u'id': u'USLACKBOT',
                                                         u'is_primary_owner': False}]}
